spring:
  profiles:
    default: local

---
spring:
  config:
    activate:
      on-profile: local
  sql:
    init:
      mode: always
      platform: mysql # 이거 없으면 mysql 인식 못함

  jwt: # CLI 명령어 - openssl rand -base64 32 로 생성된 값
    secret: VZvl0mIgwU2UmDMXqa7CL79kdBUYz+IvHQWmNsWT4uA=

  datasource:
    url: jdbc:mysql://localhost:3306/MarketBridge
    username: objects
    password: 1234

#  datasource:
#    url: jdbc:h2:tcp://localhost/~/Marketbridge
#    username: sa
#    password:

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    defer-datasource-initialization: true # (2.5~) Hibernate 초기화 이후 data-mysql.sql 실행
    # 이게 없으면 data-mysql.sql 스크립트가 수행 안 되고 에러 발생합니당.

  h2:
    console:
      enabled: true

  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    org.hibernate.sql: debug




payment:
  kakao:
    admin_key : "38ef7d9f7a2a2a43c93de1f5bb3ea2f5"
    test_api_key : "13d26c106e60b48a0ae5d8280e0ceb10"
    approval_url : "http://localhost:8080/payments/kakao/approval"
    cancel_url : "http://localhost:8080/payments/kakao/cancel"
    fail_url : "http://localhost:8080/payments/kakao/fail"
    one_time: # 단건 결제
      cid : "TC0ONETIME"
    subs: # 정기 결제
      cid :
---

spring:
  config:
    activate:
      on-profile: test

  data:
    redis:
      host: localhost
      port: 6379

  sql:
    init:
      mode: always
      platform: h2

  jwt: # CLI 명령어 - openssl rand -base64 32 로 생성된 값
    secret: VZvl0mIgwU2UmDMXqa7CL79kdBUYz+IvHQWmNsWT4uA=

  datasource:
    url: jdbc:h2:mem:~/Marketbridge
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true

logging:
  level:
    org.hibernate.sql: debug

payment:
  kakao:
    admin_key: "38ef7d9f7a2a2a43c93de1f5bb3ea2f5"
    test_api_key: "13d26c106e60b48a0ae5d8280e0ceb10"
    approval_url: "http://localhost:8080/payments/kakao/approval"
    cancel_url: "http://localhost:8080/payments/kakao/cancel"
    fail_url: "http://localhost:8080/payments/kakao/fail"
    one_time: # 단건 결제
      cid: "TC0ONETIME"
    subs : # 정기 결제
      cid :